name: Deloy to COS
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          wget -nv https://github.com/gohugoio/hugo/releases/download/v0.100.2/hugo_0.100.2_Linux-64bit.tar.gz -O hugo.tar.gz
          mkdir $HOME/hugo
          tar -zxvf hugo.tar.gz -C $HOME/hugo          

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install coscmd
        run: |
          pip install coscmd

      - name: deploy
        env:
          COS_BUCKET_NAME: wsyu-acm-1251414174
          COS_BUCKET_LOCATION: ap-chengdu
        run: |
          export PATH=$HOME/hugo:$PATH
          coscmd config -a ${{secrets.COS_SECRET_ID}} -s ${{secrets.COS_SECRET_KEY}} -b ${COS_BUCKET_NAME} -r ${COS_BUCKET_LOCATION} -m 10
          coscmd upload -r -s public/ /

